### ISSUE TITLE
Enable usage with certmagic only

### ISSUE THREAD

**Issue by camillsir** [gamalan/caddy-tlsredis#10]
Hey, I'm using certmagic in a standalone application without the context of the caddy framework. I would like to use this library to provide a shared tls cache using redis, but I'm having trouble doing this as the Provision method requires a caddy.Context with a populated cfg attribute [1].

Would it be possible to implement a method that instantiates the client, but without requiring the caddy context? A similiar storage plugin, tlsconsul, does this by implementing a New method that doesn't have any caddy specific dependencies [2] and thereby allowing non-caddy applications to instantiate the client.

[1] https://github.com/gamalan/caddy-tlsredis/blob/master/storageredis.go#L245
[2] https://github.com/pteich/caddy-tlsconsul/blob/master/storage.go#L26

**Comment by gamalan** [comment]
@camillsir I just change the method visibility. You could use `BuildRedisClient` method[1] after setup the necessary config, or you could gather from environment variable using `GetConfigValue` method[2]. Hope this help your case.

[1] https://github.com/gamalan/caddy-tlsredis/blob/master/storageredis.go#L347
[2] https://github.com/gamalan/caddy-tlsredis/blob/master/storageredis.go#L256

**Comment by camillsir** [comment]
That works for me, thank you.
