### ISSUE TITLE
Please add your plugin to https://caddyserver.com/download

### ISSUE THREAD

**Issue by francislavoie** [gamalan/caddy-tlsredis#12]
Caddy v2 has a new download page https://caddyserver.com/download, please sign up for an account and add this plugin there, so users can pick it for a custom build.

**Comment by gamalan** [comment]
Ah, sorry. Been busy for a while and forget to check up on it. Thank you
for the reminder.

**Comment by gamalan** [comment]
Already add it to caddyserver.com for easy setup. Gonna update the documentation later.
