### ISSUE TITLE
Add import/export command

### ISSUE THREAD

**Issue by masipcat** [gamalan/caddy-tlsredis#19]
Hi @gamalan,

First of all, thank you for the library. It's awesome!

I wanted to migrate an existing caddy installation using the storage filesystem to use redis. I wrote a simple command to import from fs to redis and another to export. Do you think it's interesting to have the cmd in this library? I can open a PR with this

**Comment by gamalan** [comment]
Technically I've been thinking about that too, and already wrote some lines
but somehow got distracted by my real job. IMO, it should be written as a
standalone cli command.

**Comment by masipcat** [comment]
I opened a PR with what I implemented so far. We can discuss if this is what you had in mind

**Comment by masipcat** [comment]
In case anyone else needs to import/export, here is the link to the [caddy-storage-migrator](https://github.com/masipcat/caddy-storage-migrator)
