### ISSUE TITLE
Add TLS option

### ISSUE THREAD

**Issue by mxrlkn** [gamalan/caddy-tlsredis#2]
Hi.

I'm trying to connect to a managed Redis instance on DigitalOcean and it requires the tls option to be enabled.

I think it's here the option is needed:
https://github.com/gamalan/caddy-tlsredis/blob/master/storageredis.go#L53

I would have made a pull request but I'm not proficient enough in go.

**Comment by gamalan** [comment]
Okay, I will fix it later. Thank you.
