### ISSUE TITLE
Runtime env variables {env.VARIABLE_NAME} are not loaded

### ISSUE THREAD

**Issue by crysper** [gamalan/caddy-tlsredis#21]
Hey,

If I'm putting something like this on the JSON  config file instead of using Caddyfile the variables are not parsed even though in other parts of the config are parsed ok.

I get this error:
`"logger":"caddy.storage.redis","msg":"TLS Storage are using Redis, on {env.REDIS_HOST}:6379"}

I'm using Caddy version 2.2.2
Running on systemctl service with:
 ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/caddyfile.json
`

**Comment by gamalan** [comment]
Can you elaborate more? Do you use JSON Configuration, Caddyfile, or ENV
variables? How do you write it?

**Comment by TekVanDo** [comment]
Same on my side, I use json configuration, and {env.VAR_NAME} don`t work in storage part of config

**Comment by gamalan** [comment]
@TekVanDo can you post your config and logs?

**Comment by TekVanDo** [comment]
Config 
`{
  "apps": {
    "http": {
      "servers": {
        "myserver": {
          "listen": [
            ":8080"
          ],
          "logs": {},
          "routes": [
            {
              "handle": [
                {
                  "handler": "reverse_proxy",
                  "upstreams": [
                    {
                      "dial": "{env.REDIRECT_ADDRESS}"
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    },
    "tls": {
      "automation": {
        "on_demand": {
          "ask": "{env.SITE_ADDRESS}/proxyCheck"
        },
        "policies": [
          {
            "issuers": [
              {
                "module": "acme",
                "email": "${env.EMAIL}"
              }
            ],
            "on_demand": true
          }
        ]
      }
    }
  },
  "storage": {
    "address": "{env.REDIS_ADDRESS}",
    "db": 0,
    "host": "redis",
    "key_prefix": "{env.REDIS_KEY_PREFIX}",
    "module": "redis",
    "password": "",
    "port": "{env.REDIS_PORT}",
    "value_prefix": "{env.REDIS_VALUE_PREFIX}"
  }
}
`
And i got an error is - "run: loading initial config: loading new config: loading storage module: loading module 'redis': provision caddy.storage.redis: dial tcp: address {env.REDIS_ADDRESS}: missing port in address"

if I change {env.REDIS_ADDRESS} to  ENV variable value (ip + port) all works fine.

**Comment by gamalan** [comment]
@TekVanDo @crysper can you test the new release (v0.2.9)?

**Comment by TekVanDo** [comment]
@gamalan thanks for a fix it is wokring.

**Comment by TekVanDo** [comment]
@gamalan seems fix don`t helped(

**Comment by gamalan** [comment]
@TekVanDo you shouldn't use address, but split it in host and port
