### ISSUE TITLE
Adding support for username with Redis 6

### ISSUE THREAD

**Issue by lpellegr** [gamalan/caddy-tlsredis#22]
It looks like it is not possible to pass a username to connect to a Redis 6 instance that supports ACLs.

I tried cheating by appending the username using the host or address configuration fields but this fails:

```
username@host
username@host:port
```

Unfortunately, I have no experience with Go. However, I noticed there is a new option called `Username` with the Go library this caddy plugin is using. Here is the PR that added the option last May:

https://github.com/go-redis/redis/pull/1325

It would be really convenient to add support since using a username is now the recommended approach.

**Comment by gamalan** [comment]
noted, i'll add it in a while

**Comment by gamalan** [comment]
please check [newest release](https://github.com/gamalan/caddy-tlsredis/releases/tag/v0.2.6)  @lpellegr

**Comment by lpellegr** [comment]
@gamalan I just tried the new release and it is working fine. Thanks!
