### ISSUE TITLE
No way to prevent encryption

### ISSUE THREAD

**Issue by idontusenumbers** [gamalan/caddy-tlsredis#23]
There seems to be code that skips the encryption if the key is empty but I see no way to set an empty key.

Setting the `aes_key` config to an empty string causes the storage engine to pick the default key. Caddy config dump will print out the empty string but debug log shows the engine is using the default key.

Setting `aes_key` config to an invalid key causes it to error while loading.

**Comment by gamalan** [comment]
please check [newest release](https://github.com/gamalan/caddy-tlsredis/releases/tag/v0.2.6) @idontusenumbers
