### ISSUE TITLE
cannot find module providing package go.opentelemetry.io/otel/label

### ISSUE THREAD

**Issue by culov** [gamalan/caddy-tlsredis#27]
When using xcaddy as follows:

`/etc/xcaddy build master --with github.com/gamalan/caddy-tlsredis`

the build fails with the following error:

```
github.com/gamalan/caddy-tlsredis imports
	github.com/go-redis/redis/v8 imports
	go.opentelemetry.io/otel/label: cannot find module providing package go.opentelemetry.io/otel/label
2021/09/01 03:56:09 [FATAL] exit status 1
```

It appears that `label` was removed from `go.opentelemetry.io/otel/`, but the redis import is still looking for it.

I've tried several things, including [this suggestion](https://github.com/go-redis/redis/issues/1534#issuecomment-779927048), but none of them have worked - I am new to Go so I'm not sure where to go from here. Can someone please point me in the right direction?

**Comment by gamalan** [comment]
Uhm, seems I need to update the go-redis version. Thanks for the report.

**Comment by culov** [comment]
> Uhm, seems I need to update the go-redis version. Thanks for the report.

Thanks for updating that! I'm still seeing the same error at the moment after re-running the command. I've tried both `go clean -modcache` to try and clear the cache, and I've also forked the repo and tried running it that way. In both cases, I'm left with the same error:

```
github.com/gamalan/caddy-tlsredis imports
	github.com/go-redis/redis/v8 imports
	go.opentelemetry.io/otel/label: cannot find module providing package go.opentelemetry.io/otel/label
```

Is there anything else that I might want to look at? I'm new to Go so please forgive me if I'm missing something basic.

**Comment by culov** [comment]
Sorry, I figured it out. It started working properly when I referenced the commit in the xcaddy build command, like so:

`/etc/xcaddy build master --with github.com/caddy-dns/route53 --with github.com/gamalan/caddy-tlsredis@cb6e2c46bea8a6cafdcba76770be2a6db1200396`

**Comment by gamalan** [comment]
Forget to add new tag, should be fine if using tag v0.2.7
