### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by smebberson** [gamalan/caddy-tlsredis#28]
I've recently tried building this module with the latest Caddy version. I'm running into the following errors:

```
github.com/gamalan/caddy-tlsredis imports
        github.com/go-redis/redis/v8 imports
        go.opentelemetry.io/otel/label: cannot find module providing package go.opentelemetry.io/otel/label
2021/11/15 02:49:30 [FATAL] exit status 1
```

I'm pretty sure this has nothing to do with the latest Caddy version, but the go.opentelemetry.io/otel/label package instead.

Is this something you're able to take a look at?

**Comment by gamalan** [comment]
which version did you use?

**Comment by smebberson** [comment]
This is my Dockerfile:
```
ARG CADDY_VERSION=2.4.3
FROM caddy:${CADDY_VERSION}-builder-alpine AS builder

ARG ROUTE53_VERSION=v1.1.2
ARG TLSREDIS_VERSION=0.2.7
RUN xcaddy build \
    --with github.com/caddy-dns/route53@${ROUTE53_VERSION} \
    --with github.com/gamalan/caddy-tlsredis@${TLSREDIS_VERSION}
```

**Comment by gamalan** [comment]
You should use v0.2.7, not 0.2.7.

**Comment by smebberson** [comment]
@gamalan, that worked. I'm not sure how I missed that - thank you.
