### ISSUE TITLE
caddy storage export command always results in an empty tar file

### ISSUE THREAD

**Issue by jum** [gamalan/caddy-tlsredis#46]
I have exported my certificates on several of my caddy servers using the storage export command from the conventional file storage module and successfully imported these into the caddy-tlsredis module after editing my Caddyfile. Caddy is using the certificates now from the Redis storage module fine. But when I attempt to export all my certificates (for backup purposes) using the caddy storage export command, it does not work. I alway get an empty tar file, any ideas what this might be?

**Comment by francislavoie** [comment]
How are you running it? Are you sure the config you use with the command actually has the redis config in it? If you're passing the wrong config (e.g. one with the default storage configured) then it would find nothing. Show your CLI output and config.

**Comment by jum** [comment]
Here is a Caddyfile of a very simple node:

`
[opc@opc4 caddy]$ cat /etc/caddy/Caddyfile
{
	email jens-uwe@mager.org
	cert_issuer acme
	default_sni {system.hostname}
	storage redis {
		host "opc3.tail6f5c6.ts.net"
	}
	log {
		output file /var/log/caddy/access.log
	}
}

(defaulthdr) {
	header {
		Strict-Transport-Security "max-age=15552000; includeSubDomains;
preload"
		-Server
	}
	log
}

(naked) {
	import defaulthdr
	redir https://www.{host}{uri} 308
}

http:// {
	import defaulthdr
	redir https://{system.hostname} 308
}

{system.hostname} {
	import defaulthdr
	root * /usr/share/caddy
	file_server
}

opc4.tail6f5c6.ts.net {
	import defaulthdr
	root * /usr/share/caddy
	file_server
	handle_path /watchtower* {
		reverse_proxy * localhost:5001
	}
	handle_errors {
		respond "{uri}: {http.error.status_code} {http.error.status_text
}" {http.error.status_code}
	}
}
` 

This node is properly running and serving TLS traffic through its {system.hostname}:

`
[opc@opc4 caddy]$ sudo journalctl -a -u caddy --no-pager
Aug 08 09:49:47 opc4.mager.org systemd[1]: Starting Caddy...
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: caddy.HomeDir=/var/lib/caddy
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: caddy.AppDataDir=/var/lib/caddy/.local/share/caddy
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: caddy.AppConfigDir=/var/lib/caddy/.config/caddy
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: caddy.ConfigAutosavePath=/var/lib/caddy/.config/caddy/autosave.json
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: caddy.Version=v2.7.3 h1:eMCNjOyMgB5A1KgOzT2dXKR4I0Va+YHCJYC8HHu+DP0=
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: runtime.GOOS=linux
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: runtime.GOARCH=arm64
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: runtime.Compiler=gc
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: runtime.NumCPU=1
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: runtime.GOMAXPROCS=1
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: runtime.Version=go1.20.7
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: os.Getwd=/
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: LANG=en_US.UTF-8
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: NOTIFY_SOCKET=/run/systemd/notify
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: HOME=/var/lib/caddy
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: LOGNAME=caddy
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: USER=caddy
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: INVOCATION_ID=34fcf571f94944328ab52b114c8cc842
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: JOURNAL_STREAM=8:12729885
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: {"level":"info","ts":1691488187.9496586,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: {"level":"info","ts":1691488187.9535716,"msg":"redirected default logger","from":"stderr","to":"/var/log/caddy/access.log"}
Aug 08 09:49:47 opc4.mager.org caddy[1485501]: {"level":"info","ts":1691488187.9561567,"caller":"caddy-tlsredis@v0.2.9/storageredis.go:278","msg":"TLS Storage are using Redis, on opc3.tail6f5c6.ts.net:6379"}
Aug 08 09:49:48 opc4.mager.org systemd[1]: Started Caddy.
`

This is exporting the certs:

`
[opc@opc4 caddy]$ sudo -u caddy /usr/local/bin/caddy storage export --config /etc/caddy/Caddyfile --output /tmp/certs.tar
2023/08/08 09:54:27.276	INFO	using provided configuration	{"config_file": "/etc/caddy/Caddyfile", "config_adapter": ""}
{"level":"info","ts":1691488467.2819595,"caller":"caddy-tlsredis@v0.2.9/storageredis.go:278","msg":"TLS Storage are using Redis, on opc3.tail6f5c6.ts.net:6379"}
[opc@opc4 caddy]$ ls -l /tmp/certs.tar
-rw-r--r--. 1 caddy caddy 1024  8. Aug 09:54 /tmp/certs.tar
`

And this is actually the certificates stored in the Redis instance:

`
[opc@opc3 redis]$ ./redis-cli.sh 'keys caddytls*' |wc -l
347
`

**Comment by jum** [comment]
Somehow the copy and paste of the above code from terminal did not preserve newlines, the count of lines above is 347 from the number of keys in Redis storage.

**Comment by pberkel** [comment]
I was able to replicate the issue and discovered a fix https://github.com/gamalan/caddy-tlsredis/pull/50

**Comment by jum** [comment]
I just tried the newly tagged v0.3.0 and it does not work at all. Did not have time yet to investigate, just a heads up.

**Comment by pberkel** [comment]
@jum can you elaborate on exactly what problems you are experiencing?

**Comment by pberkel** [comment]
No problem @jum it doesn't sound like an issue that was introduced by the one-line fix for this specific problem, perhaps some other change that occurred between the version you were previously running and this one?

**Comment by jum** [comment]
@pberkel it is the patch before that, I would guess the one from @francieslavoie

**Comment by francislavoie** [comment]
How were you configuring the storage plugin before/after the fix?

**Comment by francislavoie** [comment]
I'm not sure I understand what you mean. `rd.Address` must have been empty with that config, so `ReplaceAll` must return empty string because it doesn't contain a `{` for a placeholder. It's effectively a no-op unless you specified `address` in your config.

**Comment by jum** [comment]
I may have to step further to find out what is happening.

**Comment by jum** [comment]
Ok, it boils down to a logic error in module configuration. In storageredis.go in line 296 rd.Address is set to any host and port if not set explicitly. But I did only specify a host, no port. So the value is set to "host:" without any port. But later, after all default values have been set, it is again attempted to set in line 317, but this time rd.Address is already set with the incomplete "host:" and nothing happens. I would suspect deleting line 296 would make it work. Will try that tomorrow.

**Comment by jum** [comment]
Deleting that line does indeed make it work, I was able to export my certs without needing to specify a port in my Caddyfile.

**Comment by francislavoie** [comment]
Deleting 296 would break the usecase where you use a placeholder for `address` in the config. That's why that exists.

**Comment by jum** [comment]
I am closing the issue now, fixed. An example to export all certs from a caddy docker container can be found here: [https://github.com/jum/caddy-docker-proxy-redis/commit/ed47dca12f5fd64668e55889ec72a59af4a91a56](https://github.com/jum/caddy-docker-proxy-redis/commit/ed47dca12f5fd64668e55889ec72a59af4a91a56)
