### ISSUE TITLE
KeyDB replacement for Redis

### ISSUE THREAD

**Issue by codeagencybe** [gamalan/caddy-tlsredis#5]
Can we safely replace REDIS by KeyDB? 
KeyDB is a fork of redis and they claim everything from REDIS should work exactly the same in KeyDB, except is more performant than redis (5x faster than REDIS) and supports clustering/replicatoin out of the box. 

https://keydb.dev/

**Comment by gamalan** [comment]
Not sure, haven't test it yet. Assuming the fork is working exactly the same, then it should pose no problem.
