### ISSUE TITLE
Can't build with latest version of Caddy

### ISSUE THREAD

**Issue by eddiejibson** [gamalan/caddy-tlsredis#8]
Hi,

I'm currently building via [`xcaddy`](https://github.com/caddyserver/xcaddy) which is essentially builds caddy with the option to supply the modules via command arguments.

Here's the command:

```bash
./xcaddy build --with github.com/gamalan/caddy-tlsredis --with github.com/pteich/caddy-tlsconsul 
```

However, despite no build errors popping up, I see no redis storage module showing up with `caddy list-modules`. `caddy.storage.tlsconsul` shows up fine, though. Am I using the wrong package URL? Or is there currently a bug I'm not aware of?

Same happened when I built from source without the use of `xcaddy` and straight from scratch, again using the URL `github.com/gamalan/caddy-tlsredis`.

Thanks.

**Comment by mholt** [comment]
Looks like caddy 2 support is still in a beta tag, which Go modules won't use automatically. Specificy the version manually by appending `@VERSION` to the module name (replacing VERSION with a commit or tag).

**Comment by eddiejibson** [comment]
@mholt Great, thanks. Works fine now.
